sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm test
  - npm run e2e
after_success:
  # stop build if there are any changed files
  - $(npm bin)/stop-build
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
